version: '3'

services:
  apache:
    image: php:8.1-apache
    ports:
      - "8080:80"
    volumes:
      - ./your-php-app:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8181:80"
    environment:
      PMA_HOST: apache
      PMA_PORT: 80
    depends_on:
      - apache
